spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/insure_manages
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      use_sql_comments: true
      format_sql: true
    properties:
      hibernate:
        format_sql: true
        SQL: debug
        dialect: org.hibernate.dialect.PostgreSQLDialect



  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

server:
  port: 8088
